### ISSUE TITLE
Modify install instructions

### ISSUE THREAD

**Issue by mdpiper** [gantian127/nwis#1]
In the README, the install instruction
```
pip install nwis
```
currently fails because `nwis` hasn't been built on PyPI.

After building on PyPI, it would be good to have instructions for installing a binary and installing from source, similar to what's done [here](https://github.com/csdms/babelizer/blob/develop/README.rst).

**Comment by gantian127** [comment]
@mdpiper Thanks for testing on this. The instruction doesn't work right now. Because I haven't pushed it to PyPI. I will add more instruction for other ways of installing the package. Thank you!
